import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Features from "../src/components/Features/Features";
import Footer from "../src/components/Footer/Footer";
import { Header } from "../src/components/Header/Header";
import Hero from "../src/components/Hero/Hero";
import { RecentWorks } from "../src/components/RecentWorks/RecentWorks";

const Home: NextPage = () => {
  return (
    <div
      style={{
        scrollBehavior: "smooth",
      }}
    >
      <Head>
        <title>MGS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Features />
      <RecentWorks />
      <Footer />
    </div>
  );
};

export default Home;
